{% set name = "expression" %}
{% set version = "4.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 89a23ee8b6426ef7ab9178e1896d42b2984e888c1d9038549fc98cd987cfe236

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python >=3.9,<4
  run:
    - python >=3.9,<4
    - typing-extensions >=4.1.1,<5.0.0

test:
  imports:
    - expression
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/cognitedata/Expression
  summary: Practical functional programming for Python 3.9+
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
