{% set name = "expression" %}
{% set version = "5.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3755d9115242d1b6c51f2fc6facc769b9b5ce30077abe861e836639c1e935906

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python >=3.11,<4.0
  run:
    - python >=3.11,<4.0
    - typing-extensions >=4.1.1,<5.0.0

test:
  imports:
    - expression
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/cognitedata/Expression
  summary: Practical functional programming for Python 3.9+
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
