{% set name = "expression" %}
{% set version = "4.2.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1bfb44b4b63b133abf201a23eeb800791dee239901382209f36c6b7bb4a735ff

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python >=3.9,<3.11
  run:
    - python >=3.9,<3.11
    - typing-extensions >=4.1.1,<5.0.0

test:
  imports:
    - expression
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/cognitedata/Expression
  summary: Practical functional programming for Python 3.9+
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
